CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR NOT NULL,
  "login" VARCHAR NOT NULL,
  "name" VARCHAR,
  "birthday" DATE
);

CREATE TABLE "films" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL,
  "release_date" DATE,
  "duration" INTEGER NOT NULL,
  "mpa_id" INTEGER
);

CREATE TABLE "genre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR
);

CREATE TABLE "film_genres" (
  "film_id" INTEGER,
  "genre_id" INTEGER
);

CREATE TABLE "mpa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR
);

CREATE TABLE "friend_list" (
  "user_id" INTEGER,
  "friend_id" INTEGER,
  "state" BOOLEAN
);

CREATE TABLE "likes" (
  "user_id" INTEGER,
  "film_id" INTEGER
);

ALTER TABLE "film_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "films" ADD FOREIGN KEY ("mpa_id") REFERENCES "mpa" ("id");

ALTER TABLE "friend_list" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friend_list" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");
