SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE films RESTART IDENTITY;
TRUNCATE TABLE friend_list RESTART IDENTITY;
TRUNCATE TABLE likes RESTART IDENTITY;
TRUNCATE TABLE film_genres RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;


--GIR: очистка таблиц
DELETE FROM DIRECTORS;
ALTER TABLE DIRECTORS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EVENT_TYPES;
ALTER TABLE EVENT_TYPES ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EVENTS;
ALTER TABLE EVENTS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM FILM_DIRECTORS;

DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM FRIEND_LIST;
DELETE FROM LIKES;

DELETE FROM OPERATIONS;
ALTER TABLE OPERATIONS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM REVIEW_LIKES;

DELETE FROM REVIEWS;
ALTER TABLE REVIEWS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;