--GIR: очистка таблиц
DELETE FROM DIRECTORS;
ALTER TABLE DIRECTORS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EVENTS;
ALTER TABLE EVENTS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM FILM_DIRECTORS;

DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM FRIEND_LIST;
DELETE FROM LIKES;

DELETE FROM REVIEW_LIKES;

DELETE FROM REVIEWS;
ALTER TABLE REVIEWS ALTER COLUMN ID RESTART WITH 1;

DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;